version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra:/var/lib/grafana
    user: '104'
    links:
      - prometheus
    networks:
      - observability



networks:
  observability:
    driver: bridge