version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    privileged: true
    user: root
    ports:
      - 9001:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
    restart: unless-stopped